### ISSUE TITLE
Проверить ДЗ WEB-APP

### ISSUE THREAD

**Issue by annaburnaeva** [annaburnaeva/WEB-App#1]
@coursar
мой WEB-App выдает ошибку
Подскажите, пожалуйста, в каком направлении идти
При компиляции на localhost:8080 страница не найдена

**Comment by coursar** [comment]
Нужно быть немного внимательнее:
1. Resource (а не Resourse)
2. type, а не auth
3. Следите за стектрейсами в консоли, там всё написано

см. #3
